services:
  api:
    build: .
    environment:
      AUTH_URL: "http://auth-service:8080/graphql"
    restart: on-failure
    ports:
      - '8000:8000'
    depends_on:
      - auth-service

  # postgres:
  #   image: 'postgres:latest'
  #   restart: always
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: rideme

  auth-service:
    image: ghcr.io/team-evian-fiicode25/authentication:v0.7.1
    environment:
      MANDATORYFIELDS__USERNAME: true
      MANDATORYFIELDS__PHONENUMBER: false
      MANDATORYFIELDS__EMAIL: true
      PASSWORD__INSECURE: '1'
      DATABASETYPE: mongo
      MONGO__HOSTNAME: mongo
      MONGO__PORT: 27017
      MONGO__USER: root
      MONGO__PASSWORD: root
      MONGO__DATABASE: auth
    depends_on: [mongo]

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
