services:
  api:
    build: .
    environment:
      AUTH_URL: http://auth-service:8080/graphql
      POSTGRES_CONNECTION: ${POSTGRES_CONNECTION}
    restart: on-failure
    ports:
      - '8000:8000'
    depends_on:
      - auth-service
      
  auth-service:
    image: ghcr.io/team-evian-fiicode25/authentication:v0.7.1
    ports:
      - '5095:8080'
    environment:
      MANDATORYFIELDS__USERNAME: true
      MANDATORYFIELDS__PHONENUMBER: false
      MANDATORYFIELDS__EMAIL: true
      DATABASE__MONGO__URL: ${MONGO_CONNECTION}
